name: assignment-test
on: [push]
jobs:
    unit-test:
        container: cuaesd/aesd-autotest:unit-test
        runs-on: assignment1-runner
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: Run unit test
            run: ./unit-test.sh
    full-test:
        container: cuaesd/aesd-autotest:assignment1
        runs-on: assignment1-runner
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: Run full test
            run: ./full-test.sh
